#pragma once

/* Kconfig values the esp32flight core reads, frozen for the app build */

#define CONFIG_CANFLIGHT_WIFI_SSID     ""
#define CONFIG_CANFLIGHT_WIFI_PASSWORD ""
#define CONFIG_CANFLIGHT_RADIUS_NM     54
#define CONFIG_CANFLIGHT_POLL_SECONDS  8

/* Display-port knobs referenced by the device lvgl_port.h (unused here) */
#define CONFIG_EXAMPLE_LVGL_PORT_TICK 2
#define CONFIG_EXAMPLE_LVGL_PORT_TASK_MAX_DELAY_MS 500
#define CONFIG_EXAMPLE_LVGL_PORT_TASK_MIN_DELAY_MS 10
#define CONFIG_EXAMPLE_LVGL_PORT_TASK_STACK_SIZE_KB 6
#define CONFIG_EXAMPLE_LVGL_PORT_TASK_PRIORITY 2
#define CONFIG_EXAMPLE_LVGL_PORT_TASK_CORE (-1)
#define CONFIG_EXAMPLE_LVGL_PORT_BUF_INTERNAL 1
#define CONFIG_EXAMPLE_LVGL_PORT_BUF_HEIGHT 100
#define CONFIG_EXAMPLE_LVGL_PORT_AVOID_TEAR_ENABLE 0
#define CONFIG_EXAMPLE_LVGL_PORT_ROTATION_DEGREE 0
#define CONFIG_EXAMPLE_LCD_RGB_BOUNCE_BUFFER_HEIGHT 10
